module NbaStats

  module Constants
    LEAGUE_ID_NBA                   = '00'
    LEAGUE_ID_WNBA                  = '10'
    LEAGUE_ID_DLEAGUE               = '20'
    SEASON_TYPE_REGULAR             = 'Regular Season'
    SEASON_TYPE_PLAYOFFS            = 'Playoffs'
    SEASON_TYPE_ALL_STAR            = 'All Star'
    SEASON_SEGMENT_PRE_ALL_STAR     = 'Pre All-Star'
    SEASON_SEGMENT_POST_ALL_STAR    = 'Post All-Star'
    GRAPH_STAT_POINTS               = 'PTS'
    SEASON_FIRST                    = '1946-47'
    PER_MODE_TOTALS                 = 'Totals'
    CONTEXT_MEASURE_FGM             = 'FGM'
    CONTEXT_MEASURE_FGA             = 'FGA'
    CONTEXT_MEASURE_FG_PCT          = 'FG_PCT'
    CONTEXT_MEASURE_FG3M            = 'FG3M'
    CONTEXT_MEASURE_FG3A            = 'FG3A'
    CONTEXT_MEASURE_FG3_PCT         = 'FG3_PCT'
    CONTEXT_MEASURE_PF              = 'PF'
    CONTEXT_MEASURE_EFG_PCT         = 'EFG_PCT'
    CONTEXT_MEASURE_TS_PCT          = 'TS_PCT'
    CONTEXT_MEASURE_PTS_FB          = 'PTS_FB'
    CONTEXT_MEASURE_PTS_OFF_TOV     = 'PTS_OFF_TOV'
    CONTEXT_MEASURE_PTS_2ND_CHANCE  = 'PTS_2ND_CHANCE'
    LOCATION_HOME                   = 'Home'
    LOCATION_ROAD                   = 'Road'
    OUTCOME_WIN                     = 'W'
    OUTCOME_LOSS                    = 'L'
    VS_CONFERENCE_EAST              = 'East'
    VS_CONFERENCE_WEST              = 'West'
    VS_DIVISION_ATLANTIC            = 'Atlantic'
    VS_DIVISION_CENTRAL             = 'Central'
    VS_DIVISION_NORTH_WEST          = 'Northwest'
    VS_DIVISION_PACIFIC             = 'Pacific'
    VS_DIVISION_SOUTH_EAST          = 'Southeast'
    VS_DIVISION_SOUTH_WEST          = 'Southwest'
    VS_DIVISION_EAST                = 'East'
    VS_DIVISION_WEST                = 'West'
    POSITION_GUARD                  = 'Guard'
    POSITION_CENTER                 = 'Center'
    POSITION_FORWARD                = 'Forward'
    GAME_SEGMENT_FIRST_HALF         = 'First Half'
    GAME_SEGMENT_SECOND_HALF        = 'Overtime'
    GAME_SEGMENT_OVERTIME           = 'Second Half'
  end

end